# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ff4d3e467dde6cf980799936fe9bbe0ba66fae5024dbbb53dd2f75c40497f3e14c76fd7f5f58c42b002969e7d92f3aedeb0cfceccca57f8099658a5c0c84336

test:
  secret_key_base: dd7ca959334d2a041d23d0d30f15239aa85e78bc23148ef12fbb8f9616702718f6ce239cfa53e957c6c5a33be32b7eb5fb6243842d5ffbb704c88dfb0dc9904e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
